name: todo_app
description: A feature-rich TODO application built with Clean Architecture, BLoC, and Drift.
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/

dependencies:
  flutter:
    sdk: flutter


  # State management
  flutter_bloc: ^8.1.5
  bloc: ^8.1.4

  # Persistence
  drift: ^2.18.0
  drift_flutter: ^0.2.0
  sqlite3_flutter_libs: ^0.5.24

  # DI
  get_it: ^7.7.0

  # Utilities
  equatable: ^2.0.5
  uuid: ^4.4.0
  lottie: ^3.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^2.18.0
  build_runner: ^2.4.11
  # bloc_test: ^10.0.0
  mocktail: ^1.0.4
  flutter_lints: ^4.0.0